Environment Variables
SiaFoundation/renterd pull request #234
Opened 2023-03-27 11:32 UTC by peterjan

This PR adds

- `RENTERD_BUS_GATEWAY_ADDR`
- `RENTERD_TRACING_SERVICE_INSTANCE_ID`

we were using the worker ID which no longer makes sense I think. I added `RENTERD_BUS_GATEWAY_ADDR` because I ran into it the other day and to make sure it's consistent with the other environment variables.

2023-03-27 14:08 UTC, ChrisSchinnerl requested changes

2023-03-27 14:08 UTC, ChrisSchinnerl commented on cmd/renterd/main.go
> +	flag.StringVar(&busCfg.GatewayAddr, "bus.gatewayAddr", "localhost:9981", "address to listen on for Sia peer connections - can be overwritten using RENTERD_BUS_GATEWAY_ADDR environment variable")
I think this breaks incoming connections since it's supposed to be publicly accessible. I'd stick with `:9981` as the default.

2023-03-27 14:08 UTC, ChrisSchinnerl commented on cmd/renterd/main.go
> +	tracingServiceInstanceId := flag.String("tracing-service-id", "cluster", "ID of the service instance used for tracing. If RENTERD_TRACING_SERVICE_INSTANCE_ID is set, it overwrites the CLI flag's val
`tracing-service-instance-id` is better I think since it matches the env var.

2023-03-29 06:41 UTC, peterjan commented
@n8maninger I want to change `RENTERD_WALLET_SEED` to `RENTERD_SEED`... since this affects the uploaders I wanted to run this by you. PR description mentions why I want to change it. It's just a small change but wanted to run it by you.

2023-03-29 11:34 UTC, ChrisSchinnerl approved these changes

2023-03-29 14:41 UTC, n8maninger commented
Looks good to me, I'll update the uploader once this is merged

2023-03-29 17:09 UTC, merged