Support YAML config
SiaFoundation/renterd pull request #567
Opened 2023-08-23 22:43 UTC by n8maninger

Adds support for YAML configuration files for all CLI flags and environment variables. Checks two locations for a `renterd.yml` file. If the file doesn't exist, the startup should continue as it does today.

Example:
```yml
seed: clutch cook castle mistake slush arrange horse nothing forest potato oil wash
http:
  address: 127.0.0.1:10080
  password: sia is cool
```

The priority for settings is currently:
1. default values
2. yaml
3. flags
4. environment variables

2023-08-24 13:26 UTC, ChrisSchinnerl requested changes

2023-08-24 13:34 UTC, ChrisSchinnerl commented on cmd/renterd/main.go
> +	if len(phrase) == 0 {
This breaks nodes which only have the autopilot enabled. Because right now they are not required to have the seed specified.

2023-08-25 11:24 UTC, ChrisSchinnerl approved these changes

2023-08-28 14:03 UTC, peterjan approved these changes

2023-08-28 14:25 UTC, merged